FROM python:3.7
RUN pip install --upgrade pip
RUN pip install sgqlc
#RUN pip install pymongo
#RUN pip install pylru
#RUN pip install configparser
#RUN pip install redis
#RUN pip install grpcio
RUN pip install grpcio-tools
RUN pip install graphql-core