# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loadgithub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loadgithub.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10loadgithub.proto\x12\x07service\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"i\n\x12QueryFollowRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x1a\n\x12\x66ollowingEndCursor\x18\x03 \x01(\t\x12\x19\n\x11\x66ollowerEndCursor\x18\x04 \x01(\t\"9\n\x0fQueryFollowResp\x12&\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x18.service.QueryFollowData\"S\n\x0fQueryFollowData\x12\x1d\n\x06viewer\x18\x01 \x01(\x0b\x32\r.service.Node\x12!\n\x04user\x18\x02 \x01(\x0b\x32\x13.service.GithubUser\"j\n\x04Node\x12\r\n\x05login\x18\x01 \x01(\t\x12\x13\n\x0bisSiteAdmin\x18\x02 \x01(\x08\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x10\n\x08updateAt\x18\x05 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x06 \x01(\t\"K\n\x06\x46ollow\x12\x1c\n\x05nodes\x18\x01 \x03(\x0b\x32\r.service.Node\x12#\n\x08pageInfo\x18\x02 \x01(\x0b\x32\x11.service.PageInfo\"2\n\x08PageInfo\x12\x13\n\x0bhasNextPage\x18\x01 \x01(\x08\x12\x11\n\tendCursor\x18\x02 \x01(\t\"T\n\nGithubUser\x12\"\n\tfollowing\x18\x01 \x03(\x0b\x32\x0f.service.Follow\x12\"\n\tfollowers\x18\x02 \x03(\x0b\x32\x0f.service.Follow2\x82\x01\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.service.HelloRequest\x1a\x13.service.HelloReply\"\x00\x12=\n\rSayHelloAgain\x12\x15.service.HelloRequest\x1a\x13.service.HelloReply\"\x00\x32V\n\x0cGithubLoader\x12\x46\n\x0bQueryFollow\x12\x1b.service.QueryFollowRequest\x1a\x18.service.QueryFollowResp\"\x00\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='service.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='service.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=57,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='service.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='service.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=88,
)


_QUERYFOLLOWREQUEST = _descriptor.Descriptor(
  name='QueryFollowRequest',
  full_name='service.QueryFollowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='service.QueryFollowRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='service.QueryFollowRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followingEndCursor', full_name='service.QueryFollowRequest.followingEndCursor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followerEndCursor', full_name='service.QueryFollowRequest.followerEndCursor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=195,
)


_QUERYFOLLOWRESP = _descriptor.Descriptor(
  name='QueryFollowResp',
  full_name='service.QueryFollowResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='service.QueryFollowResp.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=254,
)


_QUERYFOLLOWDATA = _descriptor.Descriptor(
  name='QueryFollowData',
  full_name='service.QueryFollowData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='viewer', full_name='service.QueryFollowData.viewer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='service.QueryFollowData.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=339,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='service.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='service.Node.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isSiteAdmin', full_name='service.Node.isSiteAdmin', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='service.Node.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='service.Node.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateAt', full_name='service.Node.updateAt', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='service.Node.company', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=447,
)


_FOLLOW = _descriptor.Descriptor(
  name='Follow',
  full_name='service.Follow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='service.Follow.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageInfo', full_name='service.Follow.pageInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=524,
)


_PAGEINFO = _descriptor.Descriptor(
  name='PageInfo',
  full_name='service.PageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hasNextPage', full_name='service.PageInfo.hasNextPage', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endCursor', full_name='service.PageInfo.endCursor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=576,
)


_GITHUBUSER = _descriptor.Descriptor(
  name='GithubUser',
  full_name='service.GithubUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='following', full_name='service.GithubUser.following', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followers', full_name='service.GithubUser.followers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=662,
)

_QUERYFOLLOWRESP.fields_by_name['data'].message_type = _QUERYFOLLOWDATA
_QUERYFOLLOWDATA.fields_by_name['viewer'].message_type = _NODE
_QUERYFOLLOWDATA.fields_by_name['user'].message_type = _GITHUBUSER
_FOLLOW.fields_by_name['nodes'].message_type = _NODE
_FOLLOW.fields_by_name['pageInfo'].message_type = _PAGEINFO
_GITHUBUSER.fields_by_name['following'].message_type = _FOLLOW
_GITHUBUSER.fields_by_name['followers'].message_type = _FOLLOW
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['QueryFollowRequest'] = _QUERYFOLLOWREQUEST
DESCRIPTOR.message_types_by_name['QueryFollowResp'] = _QUERYFOLLOWRESP
DESCRIPTOR.message_types_by_name['QueryFollowData'] = _QUERYFOLLOWDATA
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Follow'] = _FOLLOW
DESCRIPTOR.message_types_by_name['PageInfo'] = _PAGEINFO
DESCRIPTOR.message_types_by_name['GithubUser'] = _GITHUBUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

QueryFollowRequest = _reflection.GeneratedProtocolMessageType('QueryFollowRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFOLLOWREQUEST,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.QueryFollowRequest)
  })
_sym_db.RegisterMessage(QueryFollowRequest)

QueryFollowResp = _reflection.GeneratedProtocolMessageType('QueryFollowResp', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFOLLOWRESP,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.QueryFollowResp)
  })
_sym_db.RegisterMessage(QueryFollowResp)

QueryFollowData = _reflection.GeneratedProtocolMessageType('QueryFollowData', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFOLLOWDATA,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.QueryFollowData)
  })
_sym_db.RegisterMessage(QueryFollowData)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.Node)
  })
_sym_db.RegisterMessage(Node)

Follow = _reflection.GeneratedProtocolMessageType('Follow', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOW,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.Follow)
  })
_sym_db.RegisterMessage(Follow)

PageInfo = _reflection.GeneratedProtocolMessageType('PageInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAGEINFO,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.PageInfo)
  })
_sym_db.RegisterMessage(PageInfo)

GithubUser = _reflection.GeneratedProtocolMessageType('GithubUser', (_message.Message,), {
  'DESCRIPTOR' : _GITHUBUSER,
  '__module__' : 'loadgithub_pb2'
  # @@protoc_insertion_point(class_scope:service.GithubUser)
  })
_sym_db.RegisterMessage(GithubUser)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='service.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=665,
  serialized_end=795,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='service.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='service.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER


_GITHUBLOADER = _descriptor.ServiceDescriptor(
  name='GithubLoader',
  full_name='service.GithubLoader',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=797,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryFollow',
    full_name='service.GithubLoader.QueryFollow',
    index=0,
    containing_service=None,
    input_type=_QUERYFOLLOWREQUEST,
    output_type=_QUERYFOLLOWRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GITHUBLOADER)

DESCRIPTOR.services_by_name['GithubLoader'] = _GITHUBLOADER

# @@protoc_insertion_point(module_scope)
